name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        run: |
          git clone https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          cp dist/index.html dist/404.html
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r dist/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git gh-pages 